version: '3.8'

services:
  task:
    build:
      context: ./task
    networks:
      - app-network
    depends_on:
      - db

  test:
    build:
      context: ./test
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
      - ./task/orders.csv:/var/lib/mysql-files/orders.csv
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: overlay
