version: '3.8'

services:
  task:
    build:
      context: ./task
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - ORDERS_CSV_PATH=/app/orders.csv
    volumes:
      - ./task/orders.csv:/app/orders.csv  # Mount orders.csv into the task container
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  test:
    build:
      context: ./test
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
      - ./task/orders.csv:/app/orders.csv
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u user -ppassword || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
    driver: bridge